rules:
  remote: # 远程规则来源
    - 'https://raw.githubusercontent.com/kkkgo/PaoPao-Pref/main/domains.txt'
    - 'https://raw.githubusercontent.com/kkkgo/shankou/main/domains.txt'
  local: # 本地规则文件路径（相对于仓库根目录）
    - 'rule/mylist.txt'

output:
  path: 'rule/config' # 输出目录
  file: 'knightdomain.txt' # 输出文件名
