name: Update Rules and Generate Config

on:
  schedule:
    # 每天运行三次（00:00, 08:00, 16:00 UTC）
    - cron: "0 0,8,16 * * *"
  workflow_dispatch: # 手动触发
  push: # 文件更新时触发
    paths:
      - 'rule/**' # 监控 resource 文件夹中的所有文件

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载远程规则并合并
      - name: Download and merge rules
        run: |
          # 定义文件路径
          REMOTE_RULES=("https://raw.githubusercontent.com/kkkgo/PaoPao-Pref/main/domains.txt" "https://raw.githubusercontent.com/kkkgo/shankou/main/domains.txt")
          LOCAL_RULE_FILE="resource/myrule.txt"
          OUTPUT_FILE="rule/knightdomain.txt"

          # 创建输出目录
          mkdir -p rule

          # 下载远程规则
          TEMP_FILE=$(mktemp)
          for url in "${REMOTE_RULES[@]}"; do
            echo "Downloading $url..."
            curl -s "$url" >> "$TEMP_FILE"
          done

          # 合并本地规则
          echo "Merging local rules..."
          if [ -f "$LOCAL_RULE_FILE" ]; then
            cat "$LOCAL_RULE_FILE" >> "$TEMP_FILE"
          else
            echo "Local rule file not found: $LOCAL_RULE_FILE"
          fi

          # 去除注释和重复项
          echo "Removing duplicates and comments..."
          grep -vE '^\s*#|^\s*$' "$TEMP_FILE" | sort -u > "$OUTPUT_FILE"

          # 清理临时文件
          rm -f "$TEMP_FILE"

          echo "Merged rules saved to $OUTPUT_FILE"

      # 提交更改到 main 分支
      - name: Push changes to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 拉取远程 main 分支的最新内容
          git pull origin main

          # 切换到 main 分支
          git checkout main

          # 添加文件并提交
          git add rule/knightdomain.txt
          git commit -m "Updated knightdomain.txt at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

          # 推送更改到远程 main 分支
          git push origin main --force
