name: Update Rules and Generate Config

on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载远程规则并合并
      - name: Download and merge rules
        run: |
          # 定义路径
          REMOTE_RULES=("https://raw.githubusercontent.com/kkkgo/PaoPao-Pref/main/domains.txt" "https://raw.githubusercontent.com/kkkgo/shankou/main/domains.txt")
          LOCAL_RULE_FILE="resource/myrule.txt"
          OUTPUT_DIR="resource/config"
          OUTPUT_FILE="knightdomain.txt"

          # 创建输出目录
          mkdir -p "$OUTPUT_DIR"

          # 下载远程规则
          TEMP_FILE=$(mktemp)
          for url in "${REMOTE_RULES[@]}"; do
            echo "Downloading $url..."
            curl -s "$url" >> "$TEMP_FILE" || echo "Failed to download $url"
          done

          # 合并本地规则
          if [ -f "$LOCAL_RULE_FILE" ]; then
            echo "Merging local rules..."
            cat "$LOCAL_RULE_FILE" >> "$TEMP_FILE"
          else
            echo "Local rule file not found: $LOCAL_RULE_FILE"
          fi

          # 去除注释和重复项
          echo "Removing duplicates and comments..."
          grep -vE '^\s*#|^\s*$' "$TEMP_FILE" | sort -u > "$OUTPUT_DIR/$OUTPUT_FILE"

          # 调试输出
          echo "Generated rules:"
          cat "$OUTPUT_DIR/$OUTPUT_FILE"

          # 清理临时文件
          rm -f "$TEMP_FILE"

      # 提交结果到 main 分支
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add resource/config/knightdomain.txt
          git commit -m "Updated rules at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
