name: Update Rules and Generate Config

on:
  schedule:
    # 每天运行三次（00:00, 08:00, 16:00 UTC）
    - cron: "0 0,8,16 * * *"
  workflow_dispatch: # 手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 解析配置并生成规则
      - name: Parse config and generate rules
        run: |
          # 定义配置文件路径
          CONFIG_FILE="config/application.yml"

          # 解析 YAML 配置
          REMOTE_RULES=$(yq '.rules.remote[]' "$CONFIG_FILE")
          LOCAL_RULES=$(yq '.rules.local[]' "$CONFIG_FILE")
          OUTPUT_DIR=$(yq '.output.path' "$CONFIG_FILE")
          OUTPUT_FILE=$(yq '.output.file' "$CONFIG_FILE")

          # 创建输出目录
          mkdir -p "$OUTPUT_DIR"

          # 下载远程规则
          TEMP_FILE=$(mktemp)
          echo "Downloading remote rules..."
          for url in $REMOTE_RULES; do
            echo "Fetching $url"
            curl -s "$url" >> "$TEMP_FILE"
          done

          # 合并本地规则
          echo "Merging local rules..."
          for local_file in $LOCAL_RULES; do
            cat "$local_file" >> "$TEMP_FILE"
          done

          # 去除注释和重复项
          echo "Processing rules..."
          grep -vE '^\s*#|^\s*$' "$TEMP_FILE" | sort -u > "$OUTPUT_DIR/$OUTPUT_FILE"

          # 清理临时文件
          rm -f "$TEMP_FILE"

          echo "Rules saved to $OUTPUT_DIR/$OUTPUT_FILE"

      # 提交结果到 main 分支
      - name: Push changes to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add resource/config/knightdomain.txt
          git commit -m "Update knightdomain.txt"
          git push origin main
